"""Generate comprehensive auto-categorization rules for ALL categories."""

from app.database import SessionLocal
from app.models import Category, CategoryRule


RULES_BY_CATEGORY = {
    # ===== INCOME CATEGORIES =====
    "工资收入": [
        ("counterparty", "contains", "公司"),
        ("counterparty", "contains", "有限"),
        ("counterparty", "contains", "技术"),
        ("product_desc", "contains", "工资"),
        ("product_desc", "contains", "薪资"),
        ("product_desc", "contains", "代发"),
        ("product_desc", "contains", "薪酬"),
        ("product_desc", "contains", "津贴"),
        ("product_desc", "contains", "补贴"),
    ],
    "奖金绩效": [
        ("product_desc", "contains", "奖金"),
        ("product_desc", "contains", "绩效"),
        ("product_desc", "contains", "年终奖"),
        ("product_desc", "contains", "激励"),
        ("product_desc", "contains", "提成"),
        ("product_desc", "contains", "项目奖"),
    ],
    "兼职收入": [
        ("product_desc", "contains", "兼职"),
        ("product_desc", "contains", "副业"),
        ("product_desc", "contains", "咨询"),
        ("product_desc", "contains", "稿费"),
        ("product_desc", "contains", "翻译"),
        ("product_desc", "contains", "设计"),
        ("product_desc", "contains", "阿里云盘"),
        ("product_desc", "contains", "影音"),
        ("product_desc", "contains", "nas"),
        ("product_desc", "contains", "群晖"),
        ("product_desc", "contains", "synology"),
        ("product_desc", "contains", "alist"),
        ("product_desc", "contains", "emby"),
        ("product_desc", "contains", "infuse"),
        ("product_desc", "contains", "jellyfin"),
        ("product_desc", "contains", "plex"),
        ("product_desc", "contains", "网盘"),
        ("product_desc", "contains", "云盘"),
        ("product_desc", "contains", "账号"),
        ("product_desc", "contains", "共享"),
        ("product_desc", "contains", "NCode"),
        ("product_desc", "contains", "Abaqus"),
        ("product_desc", "contains", "Ansys"),
        ("product_desc", "contains", "有限元"),
        ("product_desc", "contains", "仿真"),
        ("product_desc", "contains", "CAE"),
        ("product_desc", "contains", "Python"),
        ("product_desc", "contains", "开发"),
        ("product_desc", "contains", "字幕"),
    ],
    "投资收益": [
        ("product_desc", "contains", "收益"),
        ("product_desc", "contains", "利息"),
        ("product_desc", "contains", "分红"),
        ("product_desc", "contains", "理财"),
        ("counterparty", "contains", "基金"),
        ("counterparty", "contains", "财富"),
    ],
    "理财赎回": [
        ("product_desc", "contains", "赎回"),
        ("product_desc", "contains", "卖出"),
        ("product_desc", "contains", "基金"),
    ],
    "利息收益": [
        ("product_desc", "contains", "利息"),
        ("product_desc", "contains", "收益到账"),
    ],
    "房租收入": [
        ("product_desc", "contains", "房租"),
        ("product_desc", "contains", "租金"),
        ("product_desc", "contains", "出租"),
    ],
    "礼金红包": [
        ("product_desc", "contains", "红包"),
        ("product_desc", "contains", "礼金"),
        ("product_desc", "contains", "份子"),
        ("transaction_type", "contains", "红包"),
        ("counterparty", "contains", "微信红包"),
    ],
    "退款返利": [
        ("product_desc", "contains", "退款"),
        ("product_desc", "contains", "返利"),
        ("product_desc", "contains", "返现"),
        ("product_desc", "contains", "赔付"),
        ("product_desc", "contains", "理赔"),
        ("product_desc", "contains", "退费"),
        ("counterparty", "contains", "闲鱼"),
        ("counterparty", "contains", "转转"),
    ],
    "报销款": [
        ("product_desc", "contains", "报销"),
        ("product_desc", "contains", "差旅"),
        ("product_desc", "contains", "垫付"),
        ("product_desc", "contains", "费用报销"),
    ],
    "转账收入": [
        ("product_desc", "contains", "转账收款"),
        ("product_desc", "contains", "零钱收款"),
        ("product_desc", "contains", "扫二维码"),
        ("product_desc", "contains", "赞赏码"),
        ("product_desc", "contains", "转账汇款"),
        ("product_desc", "contains", "汇入"),
    ],
    "其他收入": [
        # Fallback — no specific rules, catches what slips through
    ],

    # ===== EXPENSE CATEGORIES =====
    "餐饮美食": [
        ("counterparty", "contains", "美团"),
        ("counterparty", "contains", "饿了么"),
        ("counterparty", "contains", "肯德基"),
        ("counterparty", "contains", "麦当劳"),
        ("counterparty", "contains", "星巴克"),
        ("counterparty", "contains", "瑞幸"),
        ("counterparty", "contains", "喜茶"),
        ("counterparty", "contains", "奈雪"),
        ("counterparty", "contains", "海底捞"),
        ("counterparty", "contains", "必胜客"),
        ("counterparty", "contains", "汉堡王"),
        ("counterparty", "contains", "华莱士"),
        ("counterparty", "contains", "萨莉亚"),
        ("counterparty", "contains", "蜜雪冰城"),
        ("counterparty", "contains", "一点点"),
        ("counterparty", "contains", "coco"),
        ("counterparty", "contains", "茶百道"),
        ("counterparty", "contains", "霸王茶姬"),
        ("counterparty", "contains", "古茗"),
        ("counterparty", "contains", "食品"),
        ("counterparty", "contains", "餐饮"),
        ("counterparty", "contains", "饭店"),
        ("counterparty", "contains", "餐厅"),
        ("counterparty", "contains", "小吃"),
        ("counterparty", "contains", "烧烤"),
        ("counterparty", "contains", "火锅"),
        ("counterparty", "contains", "面馆"),
        ("counterparty", "contains", "食堂"),
        ("product_desc", "contains", "外卖"),
        ("product_desc", "contains", "餐饮"),
        ("product_desc", "contains", "食堂"),
        ("product_desc", "contains", "餐费"),
        ("product_desc", "contains", "快餐"),
        ("product_desc", "contains", "奶茶"),
        ("product_desc", "contains", "咖啡"),
    ],
    "交通出行": [
        ("counterparty", "contains", "滴滴"),
        ("counterparty", "contains", "铁路"),
        ("counterparty", "contains", "中国石化"),
        ("counterparty", "contains", "中石油"),
        ("counterparty", "contains", "高德"),
        ("counterparty", "contains", "地铁"),
        ("counterparty", "contains", "公交"),
        ("counterparty", "contains", "一嗨"),
        ("counterparty", "contains", "租车"),
        ("counterparty", "contains", "高速"),
        ("counterparty", "contains", "公路"),
        ("counterparty", "contains", "收费"),
        ("counterparty", "contains", "航空"),
        ("counterparty", "contains", "石油"),
        ("counterparty", "contains", "石化"),
        ("counterparty", "contains", "加油站"),
        ("product_desc", "contains", "ETC"),
        ("product_desc", "contains", "停车"),
        ("product_desc", "contains", "打车"),
        ("product_desc", "contains", "快车"),
        ("product_desc", "contains", "顺风车"),
        ("product_desc", "contains", "加油"),
        ("product_desc", "contains", "火车票"),
        ("product_desc", "contains", "机票"),
        ("product_desc", "contains", "高铁"),
        ("product_desc", "contains", "动车"),
        ("product_desc", "contains", "公交"),
        ("product_desc", "contains", "地铁"),
        ("product_desc", "contains", "通行费"),
        ("product_desc", "contains", "过路费"),
        ("product_desc", "contains", "乘车"),
        ("product_desc", "contains", "汽车"),
        ("product_desc", "contains", "客车"),
        ("product_desc", "contains", "轿车"),
    ],
    "购物消费": [
        ("counterparty", "contains", "淘宝"),
        ("counterparty", "contains", "京东"),
        ("counterparty", "contains", "拼多多"),
        ("counterparty", "contains", "天猫"),
        ("counterparty", "contains", "苏宁"),
        ("counterparty", "contains", "唯品会"),
        ("counterparty", "contains", "闲鱼"),
        ("counterparty", "contains", "得物"),
        ("counterparty", "contains", "当当"),
        ("counterparty", "contains", "超市"),
        ("counterparty", "contains", "便利店"),
        ("counterparty", "contains", "商场"),
        ("counterparty", "contains", "百货"),
        ("counterparty", "contains", "山姆"),
        ("counterparty", "contains", "盒马"),
        ("counterparty", "contains", "永辉"),
        ("counterparty", "contains", "大润发"),
        ("counterparty", "contains", "沃尔玛"),
        ("counterparty", "contains", "全家"),
        ("counterparty", "contains", "罗森"),
        ("counterparty", "contains", "顺丰"),
        ("counterparty", "contains", "中通"),
        ("counterparty", "contains", "圆通"),
        ("counterparty", "contains", "申通"),
        ("counterparty", "contains", "韵达"),
        ("counterparty", "contains", "极兔"),
        ("counterparty", "contains", "菜鸟"),
        ("product_desc", "contains", "购物"),
        ("product_desc", "contains", "订单"),
        ("product_desc", "contains", "商品"),
        ("product_desc", "contains", "快递"),
        ("product_desc", "contains", "包裹"),
        ("product_desc", "contains", "运费"),
    ],
    "住房物业": [
        ("counterparty", "contains", "链家"),
        ("counterparty", "contains", "自如"),
        ("counterparty", "contains", "贝壳"),
        ("counterparty", "contains", "物业"),
        ("product_desc", "contains", "房租"),
        ("product_desc", "contains", "物业"),
        ("product_desc", "contains", "维修"),
    ],
    "水电通讯": [
        ("product_desc", "contains", "电费"),
        ("product_desc", "contains", "水费"),
        ("product_desc", "contains", "燃气"),
        ("product_desc", "contains", "煤气"),
        ("product_desc", "contains", "暖气"),
        ("product_desc", "contains", "水"),
        ("product_desc", "contains", "电"),
        ("counterparty", "contains", "水务"),
        ("counterparty", "contains", "电力"),
    ],
    "通讯网络": [
        ("product_desc", "contains", "话费"),
        ("product_desc", "contains", "流量"),
        ("product_desc", "contains", "宽带"),
        ("product_desc", "contains", "固话"),
        ("counterparty", "contains", "中国移动"),
        ("counterparty", "contains", "中国联通"),
        ("counterparty", "contains", "中国电信"),
    ],
    "休闲娱乐": [
        ("counterparty", "contains", "猫眼"),
        ("counterparty", "contains", "腾讯视频"),
        ("counterparty", "contains", "爱奇艺"),
        ("counterparty", "contains", "哔哩哔哩"),
        ("counterparty", "contains", "B站"),
        ("counterparty", "contains", "网易云"),
        ("counterparty", "contains", "抖音"),
        ("counterparty", "contains", "快手"),
        ("counterparty", "contains", "Steam"),
        ("counterparty", "contains", "携程"),
        ("counterparty", "contains", "去哪儿"),
        ("counterparty", "contains", "飞猪"),
        ("counterparty", "contains", "影城"),
        ("counterparty", "contains", "影院"),
        ("product_desc", "contains", "电影"),
        ("product_desc", "contains", "演出"),
        ("product_desc", "contains", "游戏"),
        ("product_desc", "contains", "会员"),
        ("product_desc", "contains", "景区"),
        ("product_desc", "contains", "酒店"),
        ("product_desc", "contains", "民宿"),
        ("product_desc", "contains", "旅游"),
    ],
    "医疗健康": [
        ("counterparty", "contains", "医院"),
        ("counterparty", "contains", "诊所"),
        ("counterparty", "contains", "药房"),
        ("counterparty", "contains", "益丰"),
        ("counterparty", "contains", "药"),
        ("product_desc", "contains", "挂号"),
        ("product_desc", "contains", "医药"),
        ("product_desc", "contains", "病历"),
        ("product_desc", "contains", "体检"),
        ("product_desc", "contains", "药品"),
    ],
    "教育学习": [
        ("counterparty", "contains", "学校"),
        ("counterparty", "contains", "大学"),
        ("counterparty", "contains", "学院"),
        ("counterparty", "contains", "培训"),
        ("counterparty", "contains", "新东方"),
        ("counterparty", "contains", "知乎"),
        ("counterparty", "contains", "得到"),
        ("product_desc", "contains", "学费"),
        ("product_desc", "contains", "培训"),
        ("product_desc", "contains", "课程"),
        ("product_desc", "contains", "书本"),
        ("product_desc", "contains", "考试"),
    ],
    "转账红包": [
        ("transaction_type", "contains", "转账"),
        ("transaction_type", "contains", "红包"),
        ("product_desc", "contains", "转账"),
        ("product_desc", "contains", "红包"),
        ("product_desc", "contains", "零钱付款"),
        ("product_desc", "contains", "零钱支付"),
    ],
    "居家生活": [
        ("counterparty", "contains", "宜家"),
        ("counterparty", "contains", "IKEA"),
        ("product_desc", "contains", "家具"),
        ("product_desc", "contains", "沙发"),
        ("product_desc", "contains", "床垫"),
        ("product_desc", "contains", "空调"),
        ("product_desc", "contains", "冰箱"),
        ("product_desc", "contains", "洗衣机"),
        ("product_desc", "contains", "吸尘器"),
        ("product_desc", "contains", "除螨"),
    ],
    "其他支出": [
        # Fallback — no specific rules, catches what slips through
    ],
    "服饰美容": [
        ("counterparty", "contains", "屈臣氏"),
        ("counterparty", "contains", "丝芙兰"),
        ("counterparty", "contains", "Nike"),
        ("counterparty", "contains", "Adidas"),
        ("counterparty", "contains", "安踏"),
        ("counterparty", "contains", "李宁"),
        ("product_desc", "contains", "衣服"),
        ("product_desc", "contains", "鞋"),
        ("product_desc", "contains", "化妆品"),
        ("product_desc", "contains", "护肤品"),
        ("product_desc", "contains", "口红"),
        ("product_desc", "contains", "香水"),
        ("product_desc", "contains", "面膜"),
        ("product_desc", "contains", "美容"),
        ("product_desc", "contains", "理发"),
    ],
    "日用百货": [
        ("counterparty", "contains", "宜家"),
        ("counterparty", "contains", "名创优品"),
        ("counterparty", "contains", "无印良品"),
        ("product_desc", "contains", "日用品"),
        ("product_desc", "contains", "纸巾"),
        ("product_desc", "contains", "洗发"),
        ("product_desc", "contains", "沐浴"),
        ("product_desc", "contains", "洗衣"),
        ("product_desc", "contains", "清洁"),
        ("product_desc", "contains", "垃圾袋"),
        ("product_desc", "contains", "厨房"),
        ("product_desc", "contains", "收纳"),
        ("product_desc", "contains", "水杯"),
        ("product_desc", "contains", "毛巾"),
        ("product_desc", "contains", "牙刷"),
        ("product_desc", "contains", "饮料"),
        ("product_desc", "contains", "矿泉水"),
        ("product_desc", "contains", "纯净水"),
        ("product_desc", "contains", "农夫山泉"),
    ],
    "数码电器": [
        ("counterparty", "contains", "苹果"),
        ("counterparty", "contains", "华为"),
        ("counterparty", "contains", "小米"),
        ("counterparty", "contains", "OPPO"),
        ("counterparty", "contains", "vivo"),
        ("counterparty", "contains", "三星"),
        ("product_desc", "contains", "手机"),
        ("product_desc", "contains", "电脑"),
        ("product_desc", "contains", "平板"),
        ("product_desc", "contains", "电视"),
        ("product_desc", "contains", "耳机"),
        ("product_desc", "contains", "充电器"),
        ("product_desc", "contains", "数据线"),
        ("product_desc", "contains", "硬盘"),
        ("product_desc", "contains", "固态"),
        ("product_desc", "contains", "SSD"),
        ("product_desc", "contains", "内存"),
        ("product_desc", "contains", "显卡"),
        ("product_desc", "contains", "CPU"),
        ("product_desc", "contains", "主板"),
        ("product_desc", "contains", "希捷"),
        ("product_desc", "contains", "西数"),
        ("product_desc", "contains", "酷狼"),
        ("counterparty", "contains", "大疆"),
        ("counterparty", "contains", "索尼"),
    ],
    "汽车养护": [
        ("product_desc", "contains", "洗车"),
        ("product_desc", "contains", "保养"),
        ("product_desc", "contains", "维修"),
        ("product_desc", "contains", "轮胎"),
        ("product_desc", "contains", "机油"),
        ("product_desc", "contains", "车险"),
        ("product_desc", "contains", "年检"),
        ("product_desc", "contains", "违章"),
        ("product_desc", "contains", "车牌"),
        ("counterparty", "contains", "4S"),
        ("counterparty", "contains", "大众"),
        ("counterparty", "contains", "丰田"),
        ("counterparty", "contains", "本田"),
        ("counterparty", "contains", "宝马"),
        ("counterparty", "contains", "奔驰"),
        ("counterparty", "contains", "奥迪"),
        ("counterparty", "contains", "比亚迪"),
        ("counterparty", "contains", "特斯拉"),
        ("counterparty", "contains", "车管"),
        ("counterparty", "contains", "交管"),
    ],
    "运动健身": [
        ("counterparty", "contains", "keep"),
        ("counterparty", "contains", "乐刻"),
        ("counterparty", "contains", "威尔仕"),
        ("counterparty", "contains", "迪卡侬"),
        ("product_desc", "contains", "健身"),
        ("product_desc", "contains", "运动"),
        ("product_desc", "contains", "瑜伽"),
        ("product_desc", "contains", "游泳"),
        ("product_desc", "contains", "跑步"),
    ],
    "宠物": [
        ("product_desc", "contains", "猫"),
        ("product_desc", "contains", "狗"),
        ("product_desc", "contains", "宠物"),
        ("product_desc", "contains", "猫粮"),
        ("product_desc", "contains", "狗粮"),
        ("product_desc", "contains", "猫砂"),
        ("counterparty", "contains", "宠物"),
    ],
    "人情往来": [
        ("counterparty", "contains", "Xuelian"),
        ("product_desc", "contains", "红包"),
        ("product_desc", "contains", "份子"),
        ("product_desc", "contains", "礼金"),
        ("product_desc", "contains", "压岁"),
    ],
    "知识付费": [
        ("counterparty", "contains", "樊登"),
        ("counterparty", "contains", "喜马拉雅"),
        ("product_desc", "contains", "知识付费"),
        ("product_desc", "contains", "课程"),
        ("product_desc", "contains", "专栏"),
    ],

    # ===== IGNORE CATEGORIES =====
    "内部转账": [
        ("counterparty", "contains", "支付宝"),
        ("counterparty", "contains", "余额宝"),
        ("counterparty", "contains", "余利宝"),
        ("product_desc", "contains", "自动转"),
        ("product_desc", "contains", "余额转"),
        ("product_desc", "contains", "转账到"),
        ("product_desc", "contains", "转出到"),
        ("product_desc", "contains", "充值到"),
        ("product_desc", "contains", "转入"),
        ("product_desc", "contains", "余额宝"),
    ],
    "信用卡还款": [
        ("product_desc", "contains", "信用卡"),
        ("product_desc", "contains", "还款"),
        ("counterparty", "contains", "信用卡"),
    ],
    "借贷还款": [
        ("product_desc", "contains", "花呗"),
        ("product_desc", "contains", "借呗"),
        ("product_desc", "contains", "贷款"),
        ("product_desc", "contains", "还贷"),
        ("product_desc", "contains", "借款"),
    ],
    "投资理财": [
        ("product_desc", "contains", "基金"),
        ("product_desc", "contains", "ETF"),
        ("product_desc", "contains", "指数"),
        ("product_desc", "contains", "股票"),
        ("product_desc", "contains", "债券"),
        ("product_desc", "contains", "申购"),
        ("product_desc", "contains", "买入"),
        ("counterparty", "contains", "基金"),
        ("counterparty", "contains", "财富"),
        ("counterparty", "contains", "证券"),
    ],
    "账户存取": [
        ("product_desc", "contains", "提现"),
        ("product_desc", "contains", "充值"),
        ("product_desc", "contains", "存入"),
        ("product_desc", "contains", "取出"),
    ],
    "退款": [
        ("product_desc", "contains", "退款"),
        ("product_desc", "contains", "退费"),
        ("product_desc", "contains", "退回"),
        ("product_desc", "contains", "退还"),
    ],
    "其他不计收支": [
        # Fallback
    ],
}


def seed_rules():
    db = SessionLocal()
    added = 0
    skipped = 0

    try:
        cats = {c.name: c.id for c in db.query(Category).all()}
        existing_rules = {
            (r.category_id, r.field, r.pattern)
            for r in db.query(CategoryRule).all()
        }

        for cat_name, rules in RULES_BY_CATEGORY.items():
            cat_id = cats.get(cat_name)
            if not cat_id:
                print(f"  SKIP: category '{cat_name}' not found")
                continue

            for field, match_mode, pattern in rules:
                if (cat_id, field, pattern) in existing_rules:
                    skipped += 1
                    continue

                db.add(CategoryRule(
                    category_id=cat_id,
                    field=field,
                    pattern=pattern,
                    match_mode=match_mode,
                    priority=5,   # lower than user rules (100)
                ))
                added += 1

        db.commit()
        print(f"Rules seeded: {added} new, {skipped} already existed")

        # Show summary
        stats = {}
        for cat_name in RULES_BY_CATEGORY:
            cat_id = cats.get(cat_name)
            if cat_id:
                cnt = db.query(CategoryRule).filter(
                    CategoryRule.category_id == cat_id
                ).count()
                stats[cat_name] = cnt

        print("\nRules per category:")
        for name, cnt in sorted(stats.items(), key=lambda x: -x[1]):
            print(f"  {name}: {cnt} rules")

    finally:
        db.close()


if __name__ == "__main__":
    seed_rules()
